spring:
  datasource:
    url: jdbc:tc:postgresql:15:///test # instruct spring to start a postgres testcontainer to use as database during testing
    hikari:
      maximum-pool-size: 2 #https://stackoverflow.com/a/54350770

app_settings:
  github_api_endpoint: http://localhost:3000 # redirect github API requests to a running Wiremock instance
  openai_api_endpoint: http://localhost:3001 # redirect openAI API requests to a running Wiremock instance
  openai_api_key: my-fancy-key