name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  gradle-tests:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Check formatting
        run: ./gradlew --no-daemon spotlessCheck
      - name: Run tests
        run: ./gradlew --no-daemon test
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Gradle tests
          path: .build/test-results/*/*.xml
          reporter: java-junit