name: Build and update image

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Build and update image" ]
    types: [ completed ]
    branches:
      - "main"

permissions: read-all

jobs:
  build-image:
    name: Build and publish image to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_KEY }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Redeploy app
        run: "koyeb services redeploy ${{secrets.KOYEB_APP_ID}}"
